name: Back-end CI/CD

on:
  push:
    branches:
      - prod

env:
  REGION: us-central1

jobs:
        
  build-and-gar-with-gcr-deploy:
    if: contains(github.event.head_commit.message, 'backend')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: GCP Authentication
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
      - name: Debug Information
        run: |
          echo "Artifact Registry Location: ${{ secrets.GCP_AR_LOCATION }}"
          gcloud auth list
          docker info

      - name: Build and Push to Artifact Registry
        run: |
          cd backend
          docker build -t ${{ secrets.GCP_BACKEND_AR_LOCATION }} \
            --build-arg DB_URL="${{ secrets.DB_URL }}" \
            --build-arg CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
            --build-arg CLOUDINARY_KEY="${{ secrets.CLOUDINARY_KEY }}" \
            --build-arg CLOUDINARY_SECRET="${{ secrets.CLOUDINARY_SECRET }}" \
            .
          docker push ${{ secrets.GCP_BACKEND_AR_LOCATION }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tuang-tang-backendnodeapp \
            --image "${{ secrets.GCP_BACKEND_AR_LOCATION }}" \
            --platform managed \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated 
