name: Docker Compose CI/CD

on:
  push:
    branches:
      - dev-back  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo rm /usr/local/bin/docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd backend  # Change to the backend directory
          docker-compose build backendnodeapp
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker-compose push backendnodeapp
