name: Docker Image CI

on:
  push:
    branches: [ "dev-back" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # create a build kit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - # build the container image and push it to Docker \
          # Hub with the name supanuttangsin/tuang-tang-backendnodeapp
        name: Build and psuh
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          file: ./Dockerfile
          push: true
          tags: supanuttangsin/tuang-tang-backendnodeapp:latest
          
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
