name: Docker Compose CI

on:
  push:
    branches: [ "dev-back" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Compose Action              
        uses: isbang/compose-action@v1.5.1

      # - name: Clean up
      #   run: docker-compose -f docker-compose.yml down

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Compose services
        run: |
          docker ps -a
          docker images
          docker-compose -f docker-compose.yml push

    #  - name: Clean up
      #  run: docker-compose down
