name: Cloud Run Deployment

on:
  push:
    branches:
      - dev-back

env:
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/tuang-tang-411710/tuang-tang-frontendnextapp/tuang-tang-frontendnextapp-image:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: CD to frontend dir
        run: cd frontend

      - name: GCP Authentication
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # workload_identity_provider: projects/975321401382/locations/global/workloadIdentityPools/githubactions/providers/github
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          # gcloud auth configure-docker ${{ env.REGION }}.pkg.dev
          
      - name: Debug Information
        run: |
          echo "Artifact Registry Location: ${{ env.GAR_LOCATION }}"
          gcloud auth list
          docker info

      - name: Build and Push to Artifact Registry
        run: |
          cd frontend
          # gcloud config set account "$(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
          docker build -t ${{ env.GAR_LOCATION }} .
          docker push ${{ env.GAR_LOCATION }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tuang-tang-frontendnextapp-image \
            --image "${{ env.GAR_LOCATION }}" \
            --platform managed \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated  # Remove if authentication is required
