name: Cloud Run Deployment

on:
  push:
    branches:
      - dev-back

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/tuang-tang-411710/tuang-tang-frontendnextapp/tuang-tang-frontendnextapp-image:latest .
          docker push us-central1-docker.pkg.dev/tuang-tang-411710/tuang-tang-frontendnextapp/tuang-tang-frontendnextapp-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tuang-tang-frontendnextapp-image \
            --image us-central1-docker.pkg.dev/tuang-tang-411710/tuang-tang-frontendnextapp/tuang-tang-frontendnextapp-image:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated  # Remove if authentication is required
