name: Cloud Run Deployment

on:
  push:
    branches:
      - dev-back

env:
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/tuang-tang-411710/tuang-tang-frontendnextapp/tuang-tang-frontendnextapp-image:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2.0.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}.pkg.dev
          
      - name: Debug Information
        run: |
          echo "Artifact Registry Location: ${{ env.GAR_LOCATION }}"
          gcloud auth list
          docker info

      - name: Build and Push to Artifact Registry
        run: |
          cd frontend
          docker build -t ${{ env.GAR_LOCATION }} .
          docker push ${{ env.GAR_LOCATION }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tuang-tang-frontendnextapp-image \
            --image "${{ env.GAR_LOCATION }}" \
            --platform managed \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated  # Remove if authentication is required
