name: Front-end CI/CD

on:
  push:
    branches:
      - prod

env:
  REGION: us-central1

jobs:
        
  build-and-gar-with-gcr-deploy:
    if: contains(github.event.head_commit.message, 'frontend')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: CD to frontend dir
        run: cd frontend

      - name: GCP Authentication
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
      - name: Debug Information
        run: |
          echo "Artifact Registry Location: ${{ secrets.GCP_FRONTEND_AR_LOCATION }}"
          gcloud auth list
          docker info

      - name: Build and Push to Artifact Registry
        run: |
          cd frontend
          docker image prune -a
          docker build -t ${{ secrets.GCP_FRONTEND_AR_LOCATION }} \
            --build-arg NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
            --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
            --build-arg NEXT_PUBLIC_BACKEND_API="${{ secrets.NEXT_PUBLIC_BACKEND_API }}" \
            .
          docker push ${{ secrets.GCP_FRONTEND_AR_LOCATION }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tuang-tang-frontendnextapp-image \
            --image "${{ secrets.GCP_FRONTEND_AR_LOCATION }}" \
            --platform managed \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated 
